# DataPlane Agent Configuration
server:
  id: "${SERVER_ID}"
  region: "${SERVER_REGION}"
  port: 8081
  host: "0.0.0.0"

redis:
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  socket_timeout: 30
  retry_on_timeout: true
  max_connections: 10

control_plane:
  base_url: "${CONTROL_PLANE_URL}"
  api_key: "${CONTROL_PLANE_API_KEY}"
  timeout: 30
  retry_attempts: 3
  retry_backoff_factor: 2.0

monitoring:
  heartbeat_interval: 60
  metrics_port: 9090
  health_check_port: 8081
  log_level: "INFO"
  log_retention_days: 7
  command_poll_interval: 60
  command_cache_ttl: 86400

security:
  enable_tls: true
  jwt_algorithm: "RS256"
  api_key_header: "X-API-Key"
  trusted_ips: []
